# Generated by Django 4.2.3 on 2023-09-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("devicename", models.CharField(max_length=20)),
                ("deviceid", models.CharField(max_length=10)),
                ("avgcurrent", models.FloatField()),
                ("avgvoltage", models.FloatField()),
                ("totalconsumptions", models.FloatField()),
                (
                    "lastdatapoint",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Last Updated"
                    ),
                ),
                (
                    "devicestatus",
                    models.CharField(
                        choices=[("live", "Live"), ("down", "Down")],
                        default="live",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=25)),
                ("password", models.CharField(max_length=25)),
            ],
        ),
    ]
